provider_config:
  kvm:
    image: CentOS-7-x86_64-GenericCloud-1710.qcow2.xz
    image_url: https://cloud.centos.org/centos/7/images/
    ssh_pwd: c0ntrail123
    ssh_user: root
    ssh_public_key:
    ssh_private_key:
    vcpu: 12
    vram: 64000
    vdisk: 100G
    subnet_prefix: 10.4.33.17
    subnet_netmask: 255.255.255.0
    gateway: 10.4.33.0
    nameserver: 10.4.33.250
    ntpserver: 220.158.215.20
    domainsuffix: local
instances:
  kvm101:
    provider: kvm
    host: localhost
    bridge: default
    ip: 10.4.33.18
    roles:
        config_database:
        config:
        control:
        analytics_database:
        analytics:
        webui:
        k8s_master:
        kubemanager:
        openstack:
  kvm102:
    provider: kvm
    host: localhost
    bridge: default
    ip: 10.4.33.19
    roles:
        vrouter:
        k8s_node:
        openstack_compute:
  kvm103:
    provider: kvm
    host: localhost
    bridge: default
    ip: 10.4.33.20
    roles:
        vrouter:
        k8s_node:
        openstack_compute:
global_configuration:
  CONTAINER_REGISTRY: opencontrailnightly
contrail_configuration:
  CONTRAIL_VERSION: latest
  UPGRADE_KERNEL: true
  AUTH_MODE: keystone
  KEYSTONE_AUTH_URL_VERSION: /v3
  KEYSTONE_AUTH_ADMIN_PASSWORD: contrail123
  CLOUD_ORCHESTRATOR: openstack

kolla_config:
  customize:
    nova.conf: |
      [libvirt]
      virt_type=qemu
      cpu_mode=none
  kolla_globals:
    network_interface: "eth0"     #Do not change – this is the VM interface and not the host interface
    kolla_internal_vip_address: "10.4.33.18"
    kolla_external_vip_address: "10.4.33.18"
    enable_haproxy: "no"
    enable_ironic: "no"
    enable_swift: "no"
